WIP: Add script to kill slow queries in Trino
AICoE/data-hub-helpers pull request #4
Opened 2022-01-06 13:25 UTC by rimolive

2022-01-06 13:25 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **rimolive** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=AICoE%2Fdata-hub-helpers).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/AICoE/data-hub-helpers/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["rimolive"]} -->

2022-01-06 13:43 UTC, anishasthana requested changes
We will need to update the pipfile as well. Can you also add instructions for usage to the README?

2022-01-06 14:42 UTC, maulikjs commented on scripts/slow-query-killer
> +        CALL system.runtime.kill_query('{}', 'Killed by slow query killer')
can we reword the text to something like `Query timed out`

2022-04-06 16:11 UTC, sesheta commented
Issues go stale after 90d of inactivity.
Mark the issue as fresh with `/remove-lifecycle stale`.
Stale issues rot after an additional 30d of inactivity and eventually close.

If this issue is safe to close now please do so with `/close`.

/lifecycle stale

2022-05-06 17:31 UTC, sesheta commented
Stale issues rot after 30d of inactivity.
Mark the issue as fresh with `/remove-lifecycle rotten`.
Rotten issues close after an additional 30d of inactivity.

If this issue is safe to close now please do so with `/close`.

/lifecycle rotten

2022-05-09 21:53 UTC, anishasthana requested changes
Given our change of direction, I think we can close this PR. @rimolive wdyt?

2022-06-09 00:40 UTC, sesheta commented
Rotten issues close after 30d of inactivity.
Reopen the issue with `/reopen`.
Mark the issue as fresh with `/remove-lifecycle rotten`.

/close

2022-06-09 00:40 UTC, closed without merging

2022-06-09 00:40 UTC, sesheta commented
@sesheta: Closed this PR.

<details>

In response to [this](https://github.com/AICoE/data-hub-helpers/pull/4#issuecomment-1150549995):

>Rotten issues close after 30d of inactivity.
>Reopen the issue with `/reopen`.
>Mark the issue as fresh with `/remove-lifecycle rotten`.
>
>/close


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>